/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha2 "sigs.k8s.io/cluster-api/api/v1alpha2"
	scheme "sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme"
)

// MachineDeploymentStrategyTypesGetter has a method to return a MachineDeploymentStrategyTypeInterface.
// A group's client should implement this interface.
type MachineDeploymentStrategyTypesGetter interface {
	MachineDeploymentStrategyTypes(namespace string) MachineDeploymentStrategyTypeInterface
}

// MachineDeploymentStrategyTypeInterface has methods to work with MachineDeploymentStrategyType resources.
type MachineDeploymentStrategyTypeInterface interface {
	Create(*v1alpha2.MachineDeploymentStrategyType) (*v1alpha2.MachineDeploymentStrategyType, error)
	Update(*v1alpha2.MachineDeploymentStrategyType) (*v1alpha2.MachineDeploymentStrategyType, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.MachineDeploymentStrategyType, error)
	List(opts v1.ListOptions) (*v1alpha2.MachineDeploymentStrategyTypeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.MachineDeploymentStrategyType, err error)
	MachineDeploymentStrategyTypeExpansion
}

// machineDeploymentStrategyTypes implements MachineDeploymentStrategyTypeInterface
type machineDeploymentStrategyTypes struct {
	client rest.Interface
	ns     string
}

// newMachineDeploymentStrategyTypes returns a MachineDeploymentStrategyTypes
func newMachineDeploymentStrategyTypes(c *V1alpha2Client, namespace string) *machineDeploymentStrategyTypes {
	return &machineDeploymentStrategyTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineDeploymentStrategyType, and returns the corresponding machineDeploymentStrategyType object, and an error if there is any.
func (c *machineDeploymentStrategyTypes) Get(name string, options v1.GetOptions) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	result = &v1alpha2.MachineDeploymentStrategyType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineDeploymentStrategyTypes that match those selectors.
func (c *machineDeploymentStrategyTypes) List(opts v1.ListOptions) (result *v1alpha2.MachineDeploymentStrategyTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.MachineDeploymentStrategyTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineDeploymentStrategyTypes.
func (c *machineDeploymentStrategyTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a machineDeploymentStrategyType and creates it.  Returns the server's representation of the machineDeploymentStrategyType, and an error, if there is any.
func (c *machineDeploymentStrategyTypes) Create(machineDeploymentStrategyType *v1alpha2.MachineDeploymentStrategyType) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	result = &v1alpha2.MachineDeploymentStrategyType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		Body(machineDeploymentStrategyType).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineDeploymentStrategyType and updates it. Returns the server's representation of the machineDeploymentStrategyType, and an error, if there is any.
func (c *machineDeploymentStrategyTypes) Update(machineDeploymentStrategyType *v1alpha2.MachineDeploymentStrategyType) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	result = &v1alpha2.MachineDeploymentStrategyType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		Name(machineDeploymentStrategyType.Name).
		Body(machineDeploymentStrategyType).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineDeploymentStrategyType and deletes it. Returns an error if one occurs.
func (c *machineDeploymentStrategyTypes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineDeploymentStrategyTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineDeploymentStrategyType.
func (c *machineDeploymentStrategyTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	result = &v1alpha2.MachineDeploymentStrategyType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machinedeploymentstrategytypes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
