/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha2 "sigs.k8s.io/cluster-api/api/v1alpha2"
	scheme "sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme"
)

// MachineSetSpecsGetter has a method to return a MachineSetSpecInterface.
// A group's client should implement this interface.
type MachineSetSpecsGetter interface {
	MachineSetSpecs(namespace string) MachineSetSpecInterface
}

// MachineSetSpecInterface has methods to work with MachineSetSpec resources.
type MachineSetSpecInterface interface {
	Create(*v1alpha2.MachineSetSpec) (*v1alpha2.MachineSetSpec, error)
	Update(*v1alpha2.MachineSetSpec) (*v1alpha2.MachineSetSpec, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.MachineSetSpec, error)
	List(opts v1.ListOptions) (*v1alpha2.MachineSetSpecList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.MachineSetSpec, err error)
	MachineSetSpecExpansion
}

// machineSetSpecs implements MachineSetSpecInterface
type machineSetSpecs struct {
	client rest.Interface
	ns     string
}

// newMachineSetSpecs returns a MachineSetSpecs
func newMachineSetSpecs(c *V1alpha2Client, namespace string) *machineSetSpecs {
	return &machineSetSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineSetSpec, and returns the corresponding machineSetSpec object, and an error if there is any.
func (c *machineSetSpecs) Get(name string, options v1.GetOptions) (result *v1alpha2.MachineSetSpec, err error) {
	result = &v1alpha2.MachineSetSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinesetspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineSetSpecs that match those selectors.
func (c *machineSetSpecs) List(opts v1.ListOptions) (result *v1alpha2.MachineSetSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.MachineSetSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinesetspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineSetSpecs.
func (c *machineSetSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machinesetspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a machineSetSpec and creates it.  Returns the server's representation of the machineSetSpec, and an error, if there is any.
func (c *machineSetSpecs) Create(machineSetSpec *v1alpha2.MachineSetSpec) (result *v1alpha2.MachineSetSpec, err error) {
	result = &v1alpha2.MachineSetSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machinesetspecs").
		Body(machineSetSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineSetSpec and updates it. Returns the server's representation of the machineSetSpec, and an error, if there is any.
func (c *machineSetSpecs) Update(machineSetSpec *v1alpha2.MachineSetSpec) (result *v1alpha2.MachineSetSpec, err error) {
	result = &v1alpha2.MachineSetSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinesetspecs").
		Name(machineSetSpec.Name).
		Body(machineSetSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineSetSpec and deletes it. Returns an error if one occurs.
func (c *machineSetSpecs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinesetspecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineSetSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinesetspecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineSetSpec.
func (c *machineSetSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.MachineSetSpec, err error) {
	result = &v1alpha2.MachineSetSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machinesetspecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
