# See https://cloud.google.com/cloud-build/docs/build-config
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - apt-get -y update && apt-get -y --no-install-recommends install build-essential && make release-staging-latest TAG=$_GIT_TAG
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
