/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "sigs.k8s.io/cluster-api/api/v1alpha2"
)

// FakeMachineSetSpecs implements MachineSetSpecInterface
type FakeMachineSetSpecs struct {
	Fake *FakeV1alpha2
	ns   string
}

var machinesetspecsResource = schema.GroupVersionResource{Group: "v1alpha2", Version: "", Resource: "machinesetspecs"}

var machinesetspecsKind = schema.GroupVersionKind{Group: "v1alpha2", Version: "", Kind: "MachineSetSpec"}

// Get takes name of the machineSetSpec, and returns the corresponding machineSetSpec object, and an error if there is any.
func (c *FakeMachineSetSpecs) Get(name string, options v1.GetOptions) (result *v1alpha2.MachineSetSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinesetspecsResource, c.ns, name), &v1alpha2.MachineSetSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineSetSpec), err
}

// List takes label and field selectors, and returns the list of MachineSetSpecs that match those selectors.
func (c *FakeMachineSetSpecs) List(opts v1.ListOptions) (result *v1alpha2.MachineSetSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinesetspecsResource, machinesetspecsKind, c.ns, opts), &v1alpha2.MachineSetSpecList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineSetSpecList), err
}

// Watch returns a watch.Interface that watches the requested machineSetSpecs.
func (c *FakeMachineSetSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinesetspecsResource, c.ns, opts))

}

// Create takes the representation of a machineSetSpec and creates it.  Returns the server's representation of the machineSetSpec, and an error, if there is any.
func (c *FakeMachineSetSpecs) Create(machineSetSpec *v1alpha2.MachineSetSpec) (result *v1alpha2.MachineSetSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinesetspecsResource, c.ns, machineSetSpec), &v1alpha2.MachineSetSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineSetSpec), err
}

// Update takes the representation of a machineSetSpec and updates it. Returns the server's representation of the machineSetSpec, and an error, if there is any.
func (c *FakeMachineSetSpecs) Update(machineSetSpec *v1alpha2.MachineSetSpec) (result *v1alpha2.MachineSetSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinesetspecsResource, c.ns, machineSetSpec), &v1alpha2.MachineSetSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineSetSpec), err
}

// Delete takes name of the machineSetSpec and deletes it. Returns an error if one occurs.
func (c *FakeMachineSetSpecs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinesetspecsResource, c.ns, name), &v1alpha2.MachineSetSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineSetSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinesetspecsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.MachineSetSpecList{})
	return err
}

// Patch applies the patch and returns the patched machineSetSpec.
func (c *FakeMachineSetSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.MachineSetSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinesetspecsResource, c.ns, name, pt, data, subresources...), &v1alpha2.MachineSetSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineSetSpec), err
}
