/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "sigs.k8s.io/cluster-api/api/v1alpha2"
)

// FakeMachineDeploymentStrategyTypes implements MachineDeploymentStrategyTypeInterface
type FakeMachineDeploymentStrategyTypes struct {
	Fake *FakeV1alpha2
	ns   string
}

var machinedeploymentstrategytypesResource = schema.GroupVersionResource{Group: "v1alpha2", Version: "", Resource: "machinedeploymentstrategytypes"}

var machinedeploymentstrategytypesKind = schema.GroupVersionKind{Group: "v1alpha2", Version: "", Kind: "MachineDeploymentStrategyType"}

// Get takes name of the machineDeploymentStrategyType, and returns the corresponding machineDeploymentStrategyType object, and an error if there is any.
func (c *FakeMachineDeploymentStrategyTypes) Get(name string, options v1.GetOptions) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinedeploymentstrategytypesResource, c.ns, name), &v1alpha2.MachineDeploymentStrategyType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineDeploymentStrategyType), err
}

// List takes label and field selectors, and returns the list of MachineDeploymentStrategyTypes that match those selectors.
func (c *FakeMachineDeploymentStrategyTypes) List(opts v1.ListOptions) (result *v1alpha2.MachineDeploymentStrategyTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinedeploymentstrategytypesResource, machinedeploymentstrategytypesKind, c.ns, opts), &v1alpha2.MachineDeploymentStrategyTypeList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineDeploymentStrategyTypeList), err
}

// Watch returns a watch.Interface that watches the requested machineDeploymentStrategyTypes.
func (c *FakeMachineDeploymentStrategyTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinedeploymentstrategytypesResource, c.ns, opts))

}

// Create takes the representation of a machineDeploymentStrategyType and creates it.  Returns the server's representation of the machineDeploymentStrategyType, and an error, if there is any.
func (c *FakeMachineDeploymentStrategyTypes) Create(machineDeploymentStrategyType *v1alpha2.MachineDeploymentStrategyType) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinedeploymentstrategytypesResource, c.ns, machineDeploymentStrategyType), &v1alpha2.MachineDeploymentStrategyType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineDeploymentStrategyType), err
}

// Update takes the representation of a machineDeploymentStrategyType and updates it. Returns the server's representation of the machineDeploymentStrategyType, and an error, if there is any.
func (c *FakeMachineDeploymentStrategyTypes) Update(machineDeploymentStrategyType *v1alpha2.MachineDeploymentStrategyType) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinedeploymentstrategytypesResource, c.ns, machineDeploymentStrategyType), &v1alpha2.MachineDeploymentStrategyType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineDeploymentStrategyType), err
}

// Delete takes name of the machineDeploymentStrategyType and deletes it. Returns an error if one occurs.
func (c *FakeMachineDeploymentStrategyTypes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinedeploymentstrategytypesResource, c.ns, name), &v1alpha2.MachineDeploymentStrategyType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineDeploymentStrategyTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinedeploymentstrategytypesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.MachineDeploymentStrategyTypeList{})
	return err
}

// Patch applies the patch and returns the patched machineDeploymentStrategyType.
func (c *FakeMachineDeploymentStrategyTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.MachineDeploymentStrategyType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinedeploymentstrategytypesResource, c.ns, name, pt, data, subresources...), &v1alpha2.MachineDeploymentStrategyType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MachineDeploymentStrategyType), err
}
